[package]
name = "printer_geo"
version = "0.1.0"
authors = ["Eric Trombly <etrombly@yahoo.com>"]
edition = "2018"

[dependencies]
stl = "0.2.0"
byteorder = "1.3.4"
simplesvg = "0.4.0"
rayon = "1.3.1"
arrayvec = "0.5.1"
vulkano = "0.19.0"
vulkano-shaders = "0.19.0"

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "benchmark"
harness = false
