[package]
name = "printer_geo"
version = "0.1.5"
authors = ["Eric Trombly <etrombly@yahoo.com>"]
edition = "2018"

[lib]
name = "printer_geo"
crate-type = ["lib", "cdylib"]

[features]
python = ["pyo3"]

[dependencies]
stl = "0.2.0"
byteorder = "1.3.4"
simplesvg = "0.4.0"
rayon = "1.4.0"
vulkano = "0.19.0"
vulkano-shaders = "0.19.0"
nalgebra = "0.22.0"
thiserror = "1.0.20"
float-cmp = "0.8.0"

[dependencies.serde]
version = "1.0.115"
features =["derive"]

[dependencies.pyo3]
version = "0.11.1"
features = ["extension-module"]
optional = true

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "benchmark"
harness = false
